// Generates all app icons from the brand mark (assets/brand/mark.png).
// The mark is a white glyph on a solid black square — great as-is for launcher
// icons. We also derive a transparent-background version for the header so it
// can be tinted per theme via CSS mask.
// Run: node scripts/gen-icons.js   (requires sharp)
const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const MARK = path.join(ROOT, 'assets', 'brand', 'mark.png');
const assets = path.join(ROOT, 'assets');
const build = path.join(ROOT, 'build');
fs.mkdirSync(build, { recursive: true });

async function transparentMark(size, outFile) {
  // white-on-black -> use luminance as alpha on a solid-white fill
  const alpha = await sharp(MARK).resize(size, size).greyscale().toColourspace('b-w').raw().toBuffer();
  const rgba = Buffer.alloc(size * size * 4);
  for (let i = 0; i < size * size; i++) {
    rgba[i * 4] = 255; rgba[i * 4 + 1] = 255; rgba[i * 4 + 2] = 255; rgba[i * 4 + 3] = alpha[i];
  }
  await sharp(rgba, { raw: { width: size, height: size, channels: 4 } }).png().toFile(outFile);
}

async function main() {
  // Black-tile icons (favicon / PWA / Apple touch) — maskable-safe (mark is centered)
  await sharp(MARK).resize(192, 192).png().toFile(path.join(assets, 'icon-192.png'));
  await sharp(MARK).resize(512, 512).png().toFile(path.join(assets, 'icon-512.png'));
  await sharp(MARK).resize(180, 180).png().toFile(path.join(assets, 'icon-180.png'));

  // Capacitor source (Android launcher icons generated by @capacitor/assets)
  await sharp(MARK).resize(1024, 1024).png().toFile(path.join(assets, 'icon.png'));

  // Electron app icon (electron-builder derives .ico / .icns from this)
  await sharp(MARK).resize(1024, 1024).png().toFile(path.join(build, 'icon.png'));

  // Transparent white mark for the header (tinted per theme via CSS mask)
  await transparentMark(512, path.join(assets, 'brand', 'mark-alpha.png'));

  console.log('icons generated from brand/mark.png');
}
main().catch(e => { console.error(e); process.exit(1); });
